// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations (bypasses pgbouncer pooler)
    // At runtime, Next.js uses DATABASE_URL (pooler) via src/lib/prisma.ts
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
